export const ELEMENT_DATA: any[] = [
    {
        projectOwner: 'M Guinn Glazier',
        stage: 'Bid',
        projectName: 'New Toilets',
        city: 'Stansbury Park',
        state: 'UT',
        bidDate: '07/30/2018',
        completionDate: '10/01/2018',
        estimate: 53235 
    },
    {
        projectOwner: 'T Charles Metcalf',
        stage: 'Won',
        projectName: 'Build Building',
        city: 'West Valley',
        state: 'UT',
        bidDate: '12/15/2018',
        completionDate: '05/05/2019',
        estimate: 53
    },
    {projectOwner: 'R L Klay Jones',
     stage: 'Lost',
     projectName: 'Clean Gutters',
     city: 'Herriman',
     state: 'NV',
     bidDate: '09/02/2018',
     completionDate: '12/01/2018',
     estimate: 1000000 }
     ,
    {
        projectOwner: 'R L Klay Jones',
    stage: 'Possible Bid',
    projectName: 'Panda Express Renovation',
    city: 'Provo',
    state: 'CA',
    bidDate: '03/06/2018',
    completionDate: '10/01/2018',
    estimate: 621834
},
    {
        projectOwner: 'M Guinn Glazier',
        stage: 'Bid',
        projectName: 'Build Bike',
        city: 'Kanab',
        state: 'CA',
        bidDate: '08/12/2018',
        completionDate: '10/01/2018',
        estimate: 999999
    },
    {projectOwner: 'T Charles Metcalf',
    stage: 'Won',
    projectName: 'Laundry',
    city: 'St. George',
    state: 'CA',
    bidDate: '11/23/2018',
    completionDate: '06/01/2019',
    estimate: 13215
},
    {
        projectOwner: 'M Guinn Glazier',
        stage: 'Lost',
        projectName: 'Hunting',
        city: 'Tooele',
        state: 'HI',
        bidDate: '01/12/2018',
        completionDate: '07/01/2018',
        estimate: 153215
    },
    {
        projectOwner: 'R L Klay Jones',
        stage: 'Possible Bid',
        projectName: 'Drive to Cedar',
        city: 'Cedar City',
        state: 'AZ',
        bidDate: '02/14/2018',
        completionDate: '08/10/2018',
        estimate: 1212
    },
    {
        projectOwner: 'M Guinn Glazier',
        stage: 'Bid',
        projectName: 'Wash Dishes',
        city: 'Kanab',
        state: 'MA',
        bidDate: '08/29/2018',
        completionDate: '10/01/2018',
        estimate: 12000
    },
    {
        projectOwner: 'T Charles Metcalf',
        stage: 'Won',
        projectName: 'Carpet Cleaning',
        city: 'Cedar City',
        state: 'NY',
        bidDate: '10/15/2018',
        completionDate: '10/16/2018',
        estimate: 1311200
    },
    {
        projectOwner: 'M Guinn Glazier',
        stage: 'Bid',
        projectName: 'New Toilets',
        city: 'Stansbury Park',
        state: 'UT',
        bidDate: '07/30/2018',
        completionDate: '10/01/2018',
        estimate: 53235 
    },
    {
        projectOwner: 'T Charles Metcalf',
        stage: 'Won',
        projectName: 'Build Building',
        city: 'West Valley',
        state: 'UT',
        bidDate: '12/15/2018',
        completionDate: '05/05/2019',
        estimate: 53
    },
    {projectOwner: 'R L Klay Jones',
     stage: 'Lost',
     projectName: 'Clean Gutters',
     city: 'Herriman',
     state: 'NV',
     bidDate: '09/02/2018',
     completionDate: '12/01/2018',
     estimate: 1000000 }
     ,
    {
        projectOwner: 'R L Klay Jones',
    stage: 'Possible Bid',
    projectName: 'Panda Express Renovation',
    city: 'Provo',
    state: 'CA',
    bidDate: '03/06/2018',
    completionDate: '10/01/2018',
    estimate: 621834
},
    {
        projectOwner: 'M Guinn Glazier',
        stage: 'Bid',
        projectName: 'Build Bike',
        city: 'Kanab',
        state: 'CA',
        bidDate: '08/12/2018',
        completionDate: '10/01/2018',
        estimate: 999999
    },
    {projectOwner: 'T Charles Metcalf',
    stage: 'Won',
    projectName: 'Laundry',
    city: 'St. George',
    state: 'CA',
    bidDate: '11/23/2018',
    completionDate: '06/01/2019',
    estimate: 13215
},
    {
        projectOwner: 'M Guinn Glazier',
        stage: 'Lost',
        projectName: 'Hunting',
        city: 'Tooele',
        state: 'HI',
        bidDate: '01/12/2018',
        completionDate: '07/01/2018',
        estimate: 153215
    },
    {
        projectOwner: 'R L Klay Jones',
        stage: 'Possible Bid',
        projectName: 'Drive to Cedar',
        city: 'Cedar City',
        state: 'AZ',
        bidDate: '02/14/2018',
        completionDate: '08/10/2018',
        estimate: 1212
    },
    {
        projectOwner: 'M Guinn Glazier',
        stage: 'Bid',
        projectName: 'Wash Dishes',
        city: 'Kanab',
        state: 'MA',
        bidDate: '08/29/2018',
        completionDate: '10/01/2018',
        estimate: 12000
    },
    {
        projectOwner: 'T Charles Metcalf',
        stage: 'Won',
        projectName: 'Carpet Cleaning',
        city: 'Cedar City',
        state: 'NY',
        bidDate: '10/15/2018',
        completionDate: '10/16/2018',
        estimate: 1311200
    },
  ];